<?xml version="1.0" encoding="UTF-8"?>
<process xmlns="http://docs.oasis-open.org/wsbpel/2.0/process/abstract" >
	<flow name="MergedFlow">
		<links>
			<link name="callFaultProcessTOError"/>
			<link name="replyFaultTOEmpty.*"/>
		</links>
		<scope name="CH_SurScope_.*">
			<sequence>
				<assign/>
				<flow>
					<scope name="Scope_Szenario_withInvokeFHFault">
						<faultHandlers>
							<catchAll>
								<sequence>
									<assign name="Assign"/>
									<assign name="replyFault"/>
								</sequence>
							</catchAll>
						</faultHandlers>
						<sequence name="main">
							<throw name="Error">
								<targets>
									<target linkName="callFaultProcessTOError"/>
								</targets>
							</throw>
						</sequence>
					</scope>
					<flow name="CH_SurFlow_.*">
						<links/>
					</flow>
				</flow>
			</sequence>
		</scope>
		<scope name="CH_SurScope_.*">
			<variables>
				<variable name="isScopeCompleted_.*" type="ns0:boolean">
					<from expressionLanguage="urn:oasis:names:tc:wsbpel:2.0:sublang:xpath1.0">
						<![CDATA[false()]]>
					</from>
				</variable>
			</variables>
			<sequence>
				<assign>
					<copy>
						<from expressionLanguage="urn:oasis:names:tc:wsbpel:2.0:sublang:xpath1.0">
							<![CDATA[false()]]>
						</from>
						<to variable="isScopeCompleted_.*"/>
					</copy>
				</assign>
				<flow>
					<scope name="Scope_Szenario_withInvokeFH">
						<faultHandlers>
							<catchAll>
								<compensate/>
							</catchAll>
						</faultHandlers>
						<sequence name="main">
							<receive name="receiveInput"/>
							<assign name="Assign"/>
							<scope name="PRE_PROCESSING_SI_.*">
								<faultHandlers>
									<catch faultMessageType="ns:MyServiceException" faultName="ns:MyServiceException" faultVariable="faultVar">
										<sequence>
											<assign name="Assign1">
												<copy>
													<from>
														<literal>
															<impl:printInformation xmlns:impl="http://webservice.iaas.uni_stuttgart.de" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
																<impl:information>Fehler von Invoke</impl:information>
															</impl:printInformation>
														</literal>
													</from>
													<to variable="providerPrintRequest"/>
												</copy>
											</assign>
											<invoke name="Invoke"/>
										</sequence>
									</catch>
								</faultHandlers>
								<sequence>
									<assign validate="no">
										<copy>
											<from expressionLanguage="urn:oasis:names:tc:wsbpel:2.0:sublang:xpath1.0">
												<![CDATA[true()]]>
											</from>
											<to variable="isScopeCompleted_.*"/>
										</copy>
									</assign>
									<sequence>
										<assign name="callFaultProcess">
											<sources>
												<source linkName="callFaultProcessTOError"/>
											</sources>
											<copy>
												<from variable="inputInvokeFaultRequest"/>
												<to variable="input"/>
											</copy>
										</assign>
										<empty>
											<targets>
												<target linkName="replyFaultTOEmpty.*"/>
											</targets>
										</empty>
									</sequence>
								</sequence>
							</scope>
							<reply name="Reply"/>
						</sequence>
					</scope>
					<flow name="CH_SurFlow_.*">
						<links/>
						<scope name="PRE_PROCESSING_SI_.*">
							<if>
								<empty/>
							</if>
						</scope>
					</flow>
				</flow>
			</sequence>
		</scope>
	</flow>
</process>